<a href="https://colab.research.google.com/github/dharunS05/Python/blob/main/HousePrice_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
house_data = pd.read_csv("housing.csv")
house_data.head()

   longitude  latitude  ...  ocean_proximity  median_house_value
0    -122.23     37.88  ...         NEAR BAY              452600
1    -122.22     37.86  ...         NEAR BAY              358500
2    -122.24     37.85  ...         NEAR BAY              352100
3    -122.25     37.85  ...         NEAR BAY              341300
4    -122.25     37.85  ...         NEAR BAY              342200

[5 rows x 10 columns]

In [ ]:
print(house_data['ocean_proximity'].unique())

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']

In [ ]:
house_data.describe()

          longitude      latitude  ...  median_income  median_house_value
count  20640.000000  20640.000000  ...   20640.000000        20640.000000
mean    -119.569704     35.631861  ...       3.870671       206855.816909
std        2.003532      2.135952  ...       1.899822       115395.615874
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.800000     33.930000  ...       2.563400       119600.000000
50%     -118.490000     34.260000  ...       3.534800       179700.000000
75%     -118.010000     37.710000  ...       4.743250       264725.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

PreProcessing

In [ ]:
house_data['total_bedrooms'] = house_data['total_bedrooms'].fillna(house_data['total_bedrooms'].median())
house_updated = pd.get_dummies(house_data, columns=['ocean_proximity'],drop_first=True)
print(house_updated.head())

house_data.isnull().sum()

   longitude  latitude  ...  ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN
0    -122.23     37.88  ...                      True                       False
1    -122.22     37.86  ...                      True                       False
2    -122.24     37.85  ...                      True                       False
3    -122.25     37.85  ...                      True                       False
4    -122.25     37.85  ...                      True                       False

[5 rows x 13 columns]

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
median_house_value    0
dtype: int64

In [ ]:
X = house_updated.drop('median_house_value',axis=1)
y = house_updated['median_house_value']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

regressor = LinearRegression()
regressor.fit(x_train,y_train)

# Predict and evaluate
y_pred = regressor.predict(x_test)

# Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# R2 Score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

# Optional: RMSE
import numpy as np
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Squared Error: 4908476721.156606
R2 Score: 0.6254240620553614
Root Mean Squared Error (RMSE): 70060.5218447351

check Errors and accuracy

In [ ]:
data = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(data.head())

       Actual      Predicted
20046   47700   54055.448899
3024    45800  124225.338937
15663  500001  255489.379492
20484  218600  268002.431569
9814   278000  262769.434816

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

# Evaluate
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)

print("MSE:", mse)
print("R2 Score:", r2)
print("RMSE:", rmse)

MSE: 2404745975.124733
R2 Score: 0.8164888965922015
RMSE: 49038.20933848149

In [ ]:
data = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(data.head())

       Actual  Predicted
20046   47700    51521.0
3024    45800    69669.0
15663  500001   466710.4
20484  218600   247533.0
9814   278000   268110.0